### ISSUE TITLE
gpt-4 model is based on GPT-3?

### ISSUE THREAD

**Issue by dandv** [morphar/chatty-gpt#1]
![image](https://user-images.githubusercontent.com/33569/228431895-482c9a4f-aada-476a-958f-f617f6150ec9.png)

**Comment by morphar** [comment]
That is really interesting! I get the same.
Even when calling the API directly from cURL and without streaming.
In the responses from the API, when using gpt-4 as model, It even identifies by it's full name:
```
data: { ... "object":"chat.completion.chunk","created":1680202787,"model":"gpt-4-0314","choices":[...]}
```
I can only conclude, that this is not an issue with this project, but with OpenAI's API.

**Comment by morphar** [comment]
An interesting observation: Judging by the speed of the responses, it should be gpt-4 as it is slower than responses from gpt-3.
This matches what I experience, when using chat.openai.com .

Another interesting observation, is that chat.openai.com actually responds correctly, when using the gpt-4 model.

**Comment by morphar** [comment]
It's the same, when using OpenAI's playground.
I get the exact same answer, once in a while.

<img width="1350" alt="Screenshot 2023-03-30 at 21 18 30" src="https://user-images.githubusercontent.com/189420/228941380-8ad33390-b549-4602-a9a8-30d9c9926324.png">

**Comment by morphar** [comment]
It seems to be based on the cutoff date.
So according to some comments in the forums, the model doesn't know anything about gpt-4, though it actually is gpt-4, since there is no knowledge of a gpt-4 in the data it is trained on.
The ChatGPT Plus models are beta and seems to be trained on more recent data.
